### ISSUE TITLE
中文错字

### ISSUE THREAD

**Issue by b0q1** [huzichengdevelop/Book-OS#2]
https://github.com/huzichengdevelop/Book-OS/blob/82dd3d08406dc1e0ac743d3c4565374e31e92c2a/src/kernel/system.c#L41

不能再--->不能在

**Comment by hzcx998** [comment]
谢谢！


------------------



胡自成
京东少东家


 联系我









 




------------------ 原始邮件 ------------------
发件人: "boss"<notifications@github.com>;
发送时间: 2019年6月17日(星期一) 晚上11:05
收件人: "huzichengdevelop/Book-OS"<Book-OS@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [huzichengdevelop/Book-OS] 中文错字 (#2)




https://github.com/huzichengdevelop/Book-OS/blob/82dd3d08406dc1e0ac743d3c4565374e31e92c2a/src/kernel/system.c#L41
 
不能再--->不能在

**Comment by hzcx998** [comment]
我commit一下

**Comment by scientificworld** [comment]
readme里面是不是把集成开发环境打成继承开发环境了？

**Comment by hzcx998** [comment]
> readme里面是不是把集成开发环境打成继承开发环境了？

是的，打错了，我修改一些，谢谢
