### ISSUE TITLE
readme改中文吧

### ISSUE THREAD

**Issue by CharlieZheng** [huzichengdevelop/Book-OS#3]
readme中文友好更好了。

**Comment by hzcx998** [comment]
可以尝试中文英文都写上。这样都看得懂，嘻嘻


------------------



胡自成
京东少东家


 联系我









 




------------------ 原始邮件 ------------------
发件人: "boss"<notifications@github.com>;
发送时间: 2019年7月2日(星期二) 下午5:51
收件人: "huzichengdevelop/Book-OS"<Book-OS@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [huzichengdevelop/Book-OS] readme改中文吧 (#3)




readme中文友好更好了。
